# Generated by Django 4.0.7 on 2022-09-06 13:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.FileField(upload_to='receipt/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Receipt')),
                ('marked_pdf', models.FileField(blank=True, null=True, upload_to='marked-pdf/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Marked PDF')),
                ('text_clusters', models.TextField(blank=True, null=True, verbose_name='Text Clusters')),
                ('bbox_clusters', models.TextField(blank=True, null=True, verbose_name='Bbox Clusters')),
                ('blocks', models.TextField(blank=True, null=True, verbose_name='Blocks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
